#!/usr/bin/python
# -*- coding: UTF-8 -*-

import serial, time, struct

#temperatur & Feuchte Messung
import Adafruit_DHT
sensor=Adafruit_DHT.DHT22
pinTF=4

#thingspeak
import thingspeak

channel_id=236201
write_key='0IFWEXUZTP9MYY6K'
read_key='GGVY6IIWIVHSPWHL'


ser = serial.Serial()
ser.port = "/dev/ttyUSB0" # Set this to your serial port
ser.baudrate = 9600

ser.open()
ser.flushInput()

byte, lastbyte = "\x00", "\x00"

def measure(channel):
    try:
        humidity, temperature = Adafruit_DHT.read_retry(sensor, pinTF)
        # write
        response = channel.update({'field1': pm_25,'field2': pm_10,'field3': temperature, 'field4': humidity})
        
        # read
        #read = channel.get({})
        #print("Read:", read)
        
    except:
        print("connection failed")
 
 
if __name__ == "__main__":
    channel = thingspeak.Channel(id=channel_id, write_key=write_key, api_key=read_key)

while True:
	lastbyte = byte
	byte = ser.read(size=1) # We got a valid packet header
	if lastbyte == "\xAA" and byte == "\xC0":
		sentence = ser.read(size=8) # Read 8 more byte
		readings = struct.unpack('<hhxxcc',sentence) # Decode the packet - little endian, 2 shorts for pm2.5 and pm10, 2 res$   print "Readings: ", readings
		#print readings
		pm_25 = readings[0]/10
		pm_10 = readings[1]/10	
		print "PM 2.5:",pm_25,"μg/m^3  PM 10:",pm_10,"μg/m^3"
		#filename=time.strftime("%d.%b")
		#filename=filename+"_feinstaub.txt"
		#file = open(filename, "a")
		#Feuchte Temp Messung
		humidity, temperatur=Adafruit_DHT.read_retry(sensor,pinTF)
		print "Temp: ", round(temperatur,2), "C    Feuchte %: ",round (humidity,2)
		#print >> file, time.strftime("%d.%m.%Y %H:%M:%S"),"Temp(C): ,",round(temperatur,2),"Luftfeuchte(%): ,",round(humidity,1), ", PM 2.5: ,",pm_25,", μg/m^3  PM 10: ,",pm_10,", μg/m^3"
		#file.close()
	        measure(channel)
		time.sleep(60)
